version 0.2

backend:
  phases:
    install:
      commands:
        #install Node
        - echo "installing NodeJs"
        - curl -fsSL https://deb.nodesource.com/setup_12.x | bash -
        - apt install -y nodejs
    pre_build:
      commands:
        #install dependencies
        - echo installing dependencies
        - npm ci
frontend:
  phases:
    pre_build:
      commands:
        - cd client
        - npm ci
    build:
      commands:
        -npm run build
